### ISSUE TITLE
【質問】オブジェクト定義でエラーが出る件

### ISSUE THREAD

**Issue by hrtk7623** [harusys/newsh#1]
https://github.com/harusys/newsh/blob/21a25c13c446eb17a8f9b14344a6f8eeb5a09d28/weatherAPI/index.js#L28-L40

取得したデータをオブジェクト「weatehrInfo」に入れておこうと思っているのですが，
「weatehrInfo is not definedStack」というエラーが出てしまいます．．．

コメントアウトしていない部分は正常に動いて，天気情報をLINEに返せているのですが，上記気になっていて，もしお分かりであれば間違いを指摘いただきたいです

**Comment by harusys** [comment]
@hrtk7623 
原因よく分からずだけど解消したのでクローズしておいてくださいー！

**Comment by hrtk7623** [comment]
了解です！
