### ISSUE TITLE
Functions（Python）を３つ準備する

### ISSUE THREAD

**Issue by harusys** [harusys/newsh#2]
■やること
- [x] Functions（Python）を３つ準備する

■成果物
- LINE 受付 API Function　func-newsh-prod-japaneast-001
- Kawai 作業用 Function　func-kawai-test-japaneast-001
- Sao 作業用 Function　　func-sao-test-japaneast-001

**Comment by harusys** [comment]
@hrtk7623 
Functions 作成完了したので、Azure ポータル確認して問題なければクローズしておいてください！

**Comment by hrtk7623** [comment]
ありがとうございます！
承知しました！
